version: "1.0"
projectName: SIQA_GIT_1112Project
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.integrations:Test_ConnListingAndGlobalVariable
    type: flow
    stepId: /2
    reference: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.WmPackageServiceProvider.SIQAJDBCAdapterTests.adapterServices:getData
  - name: Rest_AddInt
    type: REST
    path: /drt
    action: POST
    reference: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.WmPackageServiceProvider.services:add3Ints
- runtimeAlias: SIQA_ERT_1116
  assets:
  - name: Rest_AddInt
    type: REST
    path: /ert
    action: POST
    reference: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.WmPackageServiceProvider.services:add3Ints
- runtimeAlias: SIQA_ERT_1115
  assets:
  - name: Call_testdeepclone
    type: workflow
    uid: fl6e3aa34bcf064f229f3c20b9a00db93a
    stepId: a0
    reference: project.siqa_git_1112.integrations:Test_deepclone
  - name: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.integrations:Test_ConnListingAndGlobalVariable
    type: flow
    stepId: /0
    reference: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.WmPackageServiceProvider.GB_1:readGlobalvariable
  - name: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.integrations:Test_ConnListingAndGlobalVariable
    type: flow
    stepId: /1
    reference: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.WmPackageServiceProvider.SIQACloudStreamsTests:connetorOperations
  - name: Call_TPP_Flow
    type: workflow
    uid: fleacf1b39210d4fd0aaa18136c8b703fe
    stepId: a0
    reference: services:add3Ints
