version: "1.0"
projectName: SIQA_GIT_1112Project
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.integrations:Test_ConnListingAndGlobalVariable
    type: flow
    stepId: /0
    reference: fld_111819831_stage00.projects.fl27242b8cf3454ec7868ce0298a620910.WmPackageServiceProvider.GB_1:readGlobalvariable
