version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_1112Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: SIQAJDBCAdapterTests
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_1112.integrations:Test_AlertCRTERT
  packages:
  - name: SIQA_GIT_1112Project
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 12.0.0.0.686
- serviceName: project.siqa_git_1112.integrations:Test_deepclone
  packages:
  - name: SIQA_GIT_1112Project
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.0.0.0.686
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.0.0.0.686
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.0.0.0.686
